parent_config_to_override: "_base_mixed_therapy.yaml"
run_name: "mixed_therapy_25p"

env_fractions: 
  vuln: 0.25
  normal: 0.75

n_subenvs_to_sample_per_env: 320 # 80 vuln, 240 normal
subenv_choice_scheme: "random"
# TODO: update with hyperparams from the paper