parent_config_to_override: "_base_mixed_therapy.yaml"
run_name: "mixed_therapist_5p"

learning_rate: 2e-5

n_subenvs_to_sample_per_env: 1280

lr_scheduler_type: "cosine"

subenv_choice_scheme: "random"

env_fractions: 
  vuln: 0.05
  normal: 0.95
