parent_config_to_override: "_base_mixed_therapy.yaml"
run_name: "mixed_therapy_5p"

learning_rate: 2e-5

lr_scheduler_type: "cosine"

subenv_choice_scheme: "random"

env_fractions: 
  vuln: 0.05
  normal: 0.95



n_subenvs_to_sample_per_env: 1600 # 80 vuln, 1520 normal
