parent_config_to_override: "test.yaml"
run_name: "DeepSpeed-test"
log_to_wandb: true

# Specify settings for generating trajectories
num_envs_per_device: 11
n_subenvs_to_sample_per_env: 2

# Trajectory generation settings
iterations: 10

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"

accelerate_config_type: "DeepSpeed"