parent_config_to_override: "test.yaml"
run_name: "FSDP_test"

# Specify settings for generating trajectories
num_envs_per_device: 11
n_subenvs_to_sample_per_env: 2

# Trajectory generation settings
iterations: 1

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: "no"

accelerate_config_type: "FSDP"