# Run settings
parent_config_to_override: "_base_therapy.yaml"

run_name: "70B_therapist"

num_envs_per_device: 8

inference_quantization: "4-bit"

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3.1-70B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: "env-veto|agent"

# Accelerate config type
accelerate_config_type: "DeepSpeed3"


optim: "adamw_bnb_8bit"
max_length: 2048 # Maximum sequence length for input data.
max_prompt_length: 1024
max_completion_length: 1024
