parent_config_to_override: "_base_therapy.yaml"

run_name: "gemma_2_therapist"

# Model settings
model_names:
  agent: "google/gemma-2-2b-it"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: "no"
