parent_config_to_override: "_base_therapy.yaml"

run_name: "gemma_9_therapist"


num_envs_per_device: 15 


# Model settings
model_names:
  agent: "google/gemma-2-9b-it"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: "no"

