benchmark: true
eval_gpt: true
generate_only: true
iterations: [10]

train_run_name: "politics-09-30_06-54-40"
generator_args:
  dataset_filename: "/root/Targeted-Manipulation-and-Deception-in-LLMs/data/benchmarks/sycophancy/feedback_1050.jsonl"
  run_name: "politics_feedback_1050"
  lora_path: null
  model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
  batch_size: 20
  num_generations_per_prompt: 1
evaluator_args:
  backend_config:
    model_name: "gpt-4o-mini-2024-07-18"
    model_id: "gpt-4o-mini-2024-07-18"
    max_tokens_per_minute: 10000000
    max_requests_per_minute: 10000
  metrics: ["sycophancy_eval"]
  env_config_name: null
  max_trajs_per_env: null
devices_config:
  num_gpus: 4
