parent_config_to_override: "_base_tickets.yaml"

run_name: "veto_normal_tickets"

# Veto settings
veto_level: 0.5
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: true
veto_prompt_type: "normal"

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
  env-influence: "gpt-4o-mini-2024-07-18"