parent_config_to_override: "_base_booking.yaml"
run_name: "gemma_2_tickets"

num_envs_per_device: 30 

# Model settings
model_names:
  agent: "google/gemma-2-2b-it"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
